services:
  ingress:
    image: "docker.io/traefik:v3.3"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  homepage:
    image: docker.io/joseluisq/static-web-server:2
    volumes:
      - ./services/homepage:/public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`localhost`)"
      - "traefik.http.routers.homepage.entrypoints=web"
      - traefik.http.services.homepage.loadbalancer.server.port=80

  user-service:
    build:
      context: ./services/UserService
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.user.rule=Host(`user.localhost`)"
      - "traefik.http.routers.user.entrypoints=web"
      - traefik.http.services.user.loadbalancer.server.port=80

  task-tracker:
    build:
      context: ./services/TaskTracker
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.task.rule=Host(`task.localhost`)"
      - "traefik.http.routers.task.entrypoints=web"
      - traefik.http.services.task.loadbalancer.server.port=80
